// front/futebolzinho-next/app/(main)/desculpas/page.tsx
"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { Desculpa, Jogador } from "@/lib/types";
import { useAuth } from "@/components/auth-context";

function hoje() {
  return new Date().toISOString().split("T")[0];
}

export default function DesculpasPage() {
  const { isLoggedIn } = useAuth();
  const [desculpas, setDesculpas] = useState<Desculpa[]>([]);
  const [jogadores, setJogadores] = useState<Jogador[]>([]);
  const [filtroJogadorId, setFiltroJogadorId] = useState("");
  const [filtroDataInicial, setFiltroDataInicial] = useState("");
  const [filtroDataFinal, setFiltroDataFinal] = useState("");
  const [nova, setNova] = useState<Desculpa>({
    jogadorId: "",
    jogadorNome: "",
    data: hoje(),
    descricao: "",
  });
  const [editando, setEditando] = useState<Desculpa | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function carregarJogadores() {
    const response = await api.getJogadores();
    setJogadores(response.data.sort((a, b) => a.nome.localeCompare(b.nome)));
  }

  async function carregarDesculpas() {
    try {
      setError(null);
      const response = await api.getDesculpas({
        jogadorId: filtroJogadorId || undefined,
        dataInicial: filtroDataInicial || undefined,
        dataFinal: filtroDataFinal || undefined,
      });
      setDesculpas(response.data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao carregar desculpas");
    }
  }

  useEffect(() => {
    void carregarJogadores();
    void carregarDesculpas();
  }, []);

  async function salvarNova() {
    if (!isLoggedIn) {
      setError("Faça login para registrar desculpas.");
      return;
    }
    if (!nova.jogadorId || !nova.data || !nova.descricao.trim()) {
      setError("Preencha jogador, data e descricao.");
      return;
    }
    try {
      const jogador = jogadores.find((j) => j.id === nova.jogadorId);
      const payload = { ...nova, jogadorNome: jogador?.nome ?? "" };
      await api.criarDesculpa(payload);
      setNova({ jogadorId: "", jogadorNome: "", data: hoje(), descricao: "" });
      await carregarDesculpas();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao salvar desculpa");
    }
  }

  async function salvarEdicao() {
    if (!editando?.id) return;
    try {
      const jogador = jogadores.find((j) => j.id === editando.jogadorId);
      await api.editarDesculpa(editando.id, { ...editando, jogadorNome: jogador?.nome ?? "" });
      setEditando(null);
      await carregarDesculpas();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao editar desculpa");
    }
  }

  async function excluir(id: string) {
    if (!isLoggedIn) {
      setError("Faça login para excluir desculpas.");
      return;
    }
    if (!window.confirm("Deseja excluir esta desculpa?")) return;
    try {
      await api.excluirDesculpa(id);
      await carregarDesculpas();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erro ao excluir desculpa");
    }
  }

  return (
    <div>
      <section className="card">
        <h1 className="section-title">Desculpas</h1>
        <p className="meta">Registro de ausencias com filtro por periodo e jogador.</p>
      </section>

      {error ? <section className="card error-msg">{error}</section> : null}

      <section className="card">
        <h2 style={{ marginTop: 0 }}>Filtros</h2>
        <div className="grid two">
          <label>
            Jogador
            <select value={filtroJogadorId} onChange={(e) => setFiltroJogadorId(e.target.value)}>
              <option value="">Todos</option>
              {jogadores.map((j) => (
                <option key={j.id} value={j.id}>
                  {j.nome}
                </option>
              ))}
            </select>
          </label>
          <label>
            Data inicial
            <input type="date" value={filtroDataInicial} onChange={(e) => setFiltroDataInicial(e.target.value)} />
          </label>
          <label>
            Data final
            <input type="date" value={filtroDataFinal} onChange={(e) => setFiltroDataFinal(e.target.value)} />
          </label>
        </div>
        <div className="inline-actions" style={{ marginTop: 10 }}>
          <button className="btn primary" onClick={() => void carregarDesculpas()}>
            Aplicar
          </button>
          <button
            className="btn ghost"
            onClick={() => {
              setFiltroJogadorId("");
              setFiltroDataInicial("");
              setFiltroDataFinal("");
              void carregarDesculpas();
            }}
          >
            Limpar
          </button>
        </div>
      </section>

      <section className="card">
        <h2 style={{ marginTop: 0 }}>Nova desculpa</h2>
        <div className="form-grid">
          <label>
            Jogador
            <select
              value={nova.jogadorId}
              onChange={(e) => setNova((prev) => ({ ...prev, jogadorId: e.target.value }))}
              disabled={!isLoggedIn}
            >
              <option value="">Selecione...</option>
              {jogadores.map((j) => (
                <option key={j.id} value={j.id}>
                  {j.nome}
                </option>
              ))}
            </select>
          </label>
          <label>
            Data
            <input
              type="date"
              value={nova.data}
              onChange={(e) => setNova((prev) => ({ ...prev, data: e.target.value }))}
              disabled={!isLoggedIn}
            />
          </label>
          <label>
            Descricao
            <textarea
              value={nova.descricao}
              onChange={(e) => setNova((prev) => ({ ...prev, descricao: e.target.value }))}
              disabled={!isLoggedIn}
            />
          </label>
          <button className="btn primary" onClick={() => void salvarNova()} disabled={!isLoggedIn}>
            Salvar
          </button>
        </div>
      </section>

      <section className="card">
        {desculpas.map((desculpa) => (
          <div className="list-row" key={desculpa.id}>
            <div>
              <strong>{desculpa.jogadorNome}</strong>
              <div className="meta">{new Date(`${desculpa.data}T00:00:00`).toLocaleDateString("pt-BR")}</div>
              <div>{desculpa.descricao}</div>
            </div>
            <div className="inline-actions">
              {isLoggedIn ? (
                <>
                  <button className="btn ghost" onClick={() => setEditando({ ...desculpa })}>
                    Editar
                  </button>
                  <button className="btn danger" onClick={() => void excluir(desculpa.id ?? "")}>Excluir</button>
                </>
              ) : null}
            </div>
          </div>
        ))}
      </section>

      {editando ? (
        <div className="modal-backdrop" onClick={() => setEditando(null)}>
          <div className="modal-card" onClick={(e) => e.stopPropagation()}>
            <h2>Editar desculpa</h2>
            <div className="form-grid">
              <label>
                Jogador
                <select
                  value={editando.jogadorId}
                  onChange={(e) => setEditando({ ...editando, jogadorId: e.target.value })}
                >
                  {jogadores.map((j) => (
                    <option key={j.id} value={j.id}>
                      {j.nome}
                    </option>
                  ))}
                </select>
              </label>
              <label>
                Data
                <input
                  type="date"
                  value={editando.data}
                  onChange={(e) => setEditando({ ...editando, data: e.target.value })}
                />
              </label>
              <label>
                Descricao
                <textarea
                  value={editando.descricao}
                  onChange={(e) => setEditando({ ...editando, descricao: e.target.value })}
                />
              </label>
              <div className="modal-actions">
                <button className="btn ghost" onClick={() => setEditando(null)}>Cancelar</button>
                <button className="btn primary" onClick={() => void salvarEdicao()}>Salvar</button>
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}

// front/futebolzinho-de-quinta/src/app/desculpas/desculpas.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DesculpasService, Desculpa, FiltrosDesculpa } from './desculpas.service';
import { JogadorService } from '../jogadores/jogadores.service';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-desculpas',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './desculpas.component.html',
  styleUrl: './desculpas.component.css'
})
export class DesculpasComponent implements OnInit {
  desculpas: any[] = [];
  jogadores: any[] = [];
  isLoggedIn = false;
  
  // Filtros
  filtroJogadorId: string = '';
  filtroDataInicial: string = '';
  filtroDataFinal: string = '';
  
  // Nova desculpa
  novaDesculpa: Desculpa = {
    jogadorId: '',
    jogadorNome: '',
    data: '',
    descricao: ''
  };
  
  // Edição
  desculpaEmEdicao: any = null;
  
  constructor(
    private desculpasService: DesculpasService,
    private jogadorService: JogadorService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.carregarJogadores();
    this.carregarDesculpas();
    
    this.authService.isLoggedIn.subscribe(isLoggedIn => {
      this.isLoggedIn = isLoggedIn;
    });
    
    // Definir data padrão como hoje
    const hoje = new Date().toISOString().split('T')[0];
    this.novaDesculpa.data = hoje;
  }

  carregarJogadores(): void {
    this.jogadorService.getJogadores().subscribe({
      next: (response: any) => {
        this.jogadores = response.data;
        this.jogadores.sort((a, b) => a.nome.localeCompare(b.nome));
      },
      error: (error) => {
        console.error('Erro ao carregar jogadores:', error);
        alert('Erro ao carregar jogadores');
      }
    });
  }

  carregarDesculpas(): void {
    const filtros: FiltrosDesculpa = {};
    
    if (this.filtroJogadorId) {
      filtros.jogadorId = this.filtroJogadorId;
    }
    if (this.filtroDataInicial) {
      filtros.dataInicial = this.filtroDataInicial;
    }
    if (this.filtroDataFinal) {
      filtros.dataFinal = this.filtroDataFinal;
    }
    
    this.desculpasService.getDesculpas(filtros).subscribe({
      next: (response: any) => {
        this.desculpas = response.data;
      },
      error: (error) => {
        console.error('Erro ao carregar desculpas:', error);
        alert('Erro ao carregar desculpas');
      }
    });
  }

  aplicarFiltros(): void {
    this.carregarDesculpas();
  }

  limparFiltros(): void {
    this.filtroJogadorId = '';
    this.filtroDataInicial = '';
    this.filtroDataFinal = '';
    this.carregarDesculpas();
  }

  onJogadorSelecionado(): void {
    const jogador = this.jogadores.find(j => j.id === this.novaDesculpa.jogadorId);
    if (jogador) {
      this.novaDesculpa.jogadorNome = jogador.nome;
    }
  }

  salvarDesculpa(): void {
    if (!this.novaDesculpa.jogadorId || !this.novaDesculpa.data || !this.novaDesculpa.descricao) {
      alert('Por favor, preencha todos os campos');
      return;
    }

    this.desculpasService.criarDesculpa(this.novaDesculpa).subscribe({
      next: (response: any) => {
        alert('Desculpa registrada com sucesso!');
        this.resetarFormulario();
        this.carregarDesculpas();
      },
      error: (error) => {
        console.error('Erro ao salvar desculpa:', error);
        alert('Erro ao salvar desculpa');
      }
    });
  }

  resetarFormulario(): void {
    const hoje = new Date().toISOString().split('T')[0];
    this.novaDesculpa = {
      jogadorId: '',
      jogadorNome: '',
      data: hoje,
      descricao: ''
    };
  }

  editarDesculpa(desculpa: any): void {
    this.desculpaEmEdicao = { ...desculpa };
  }

  cancelarEdicao(): void {
    this.desculpaEmEdicao = null;
  }

  salvarEdicao(): void {
    if (!this.desculpaEmEdicao) return;

    const jogador = this.jogadores.find(j => j.id === this.desculpaEmEdicao.jogadorId);
    if (jogador) {
      this.desculpaEmEdicao.jogadorNome = jogador.nome;
    }

    this.desculpasService.editarDesculpa(this.desculpaEmEdicao.id, this.desculpaEmEdicao).subscribe({
      next: (response: any) => {
        alert('Desculpa atualizada com sucesso!');
        this.desculpaEmEdicao = null;
        this.carregarDesculpas();
      },
      error: (error) => {
        console.error('Erro ao atualizar desculpa:', error);
        alert('Erro ao atualizar desculpa');
      }
    });
  }

  excluirDesculpa(id: string): void {
    if (!confirm('Tem certeza que deseja excluir esta desculpa?')) {
      return;
    }

    this.desculpasService.excluirDesculpa(id).subscribe({
      next: (response: any) => {
        alert('Desculpa excluída com sucesso!');
        this.carregarDesculpas();
      },
      error: (error) => {
        console.error('Erro ao excluir desculpa:', error);
        alert('Erro ao excluir desculpa');
      }
    });
  }

  formatarData(data: string): string {
    if (!data) return '';
    const date = new Date(data + 'T00:00:00');
    return date.toLocaleDateString('pt-BR');
  }
}

<div class="container mt-4">
  <h2 class="text-center mb-4">Desculpas dos Jogadores</h2>

  <ul class="nav nav-tabs" id="desculpasTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="listar-tab" data-bs-toggle="tab" data-bs-target="#listar"
        type="button" role="tab" aria-controls="listar" aria-selected="true">
        Listar Desculpas
      </button>
    </li>
    <li class="nav-item" role="presentation" *ngIf="isLoggedIn">
      <button class="nav-link" id="cadastrar-tab" data-bs-toggle="tab" data-bs-target="#cadastrar"
        type="button" role="tab" aria-controls="cadastrar" aria-selected="false">
        Registrar Desculpa
      </button>
    </li>
  </ul>

  <div class="tab-content" id="desculpasTabContent">
    <!-- Aba de Listagem -->
    <div class="tab-pane fade show active" id="listar" role="tabpanel" aria-labelledby="listar-tab">
      <!-- Filtros -->
      <div class="card mt-3 mb-3">
        <div class="card-header">
          <h5>Filtros</h5>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4 mb-2">
              <label for="filtroJogador" class="form-label">Jogador</label>
              <select id="filtroJogador" class="form-select" [(ngModel)]="filtroJogadorId">
                <option value="">Todos os jogadores</option>
                <option *ngFor="let jogador of jogadores" [value]="jogador.id">{{ jogador.nome }}</option>
              </select>
            </div>
            <div class="col-md-3 mb-2">
              <label for="filtroDataInicial" class="form-label">Data Inicial</label>
              <input type="date" id="filtroDataInicial" class="form-control" [(ngModel)]="filtroDataInicial">
            </div>
            <div class="col-md-3 mb-2">
              <label for="filtroDataFinal" class="form-label">Data Final</label>
              <input type="date" id="filtroDataFinal" class="form-control" [(ngModel)]="filtroDataFinal">
            </div>
            <div class="col-md-2 mb-2 d-flex align-items-end">
              <button class="btn btn-primary me-2" (click)="aplicarFiltros()">
                <i class="bi bi-funnel"></i> Filtrar
              </button>
              <button class="btn btn-secondary" (click)="limparFiltros()">
                <i class="bi bi-x-circle"></i> Limpar
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Lista de Desculpas -->
      <div class="row">
        <div class="col-12">
          <div *ngIf="desculpas.length === 0" class="alert alert-info">
            Nenhuma desculpa encontrada.
          </div>

          <div *ngFor="let desculpa of desculpas" class="card mb-3">
            <div class="card-body">
              <!-- Modo visualização -->
              <div *ngIf="!desculpaEmEdicao || desculpaEmEdicao.id !== desculpa.id">
                <div class="d-flex justify-content-between align-items-start">
                  <div class="flex-grow-1">
                    <h5 class="card-title">{{ desculpa.jogadorNome }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">
                      <i class="bi bi-calendar"></i> {{ formatarData(desculpa.data) }}
                    </h6>
                    <p class="card-text">{{ desculpa.descricao }}</p>
                  </div>
                  <div class="btn-group-vertical" *ngIf="isLoggedIn">
                    <button class="btn btn-sm btn-warning mb-1" (click)="editarDesculpa(desculpa)">
                      <i class="bi bi-pencil"></i> Editar
                    </button>
                    <button class="btn btn-sm btn-danger" (click)="excluirDesculpa(desculpa.id)">
                      <i class="bi bi-trash"></i> Excluir
                    </button>
                  </div>
                </div>
              </div>

              <!-- Modo edição -->
              <div *ngIf="desculpaEmEdicao && desculpaEmEdicao.id === desculpa.id">
                <div class="mb-3">
                  <label class="form-label">Jogador</label>
                  <select class="form-select" [(ngModel)]="desculpaEmEdicao.jogadorId">
                    <option value="">Selecione um jogador</option>
                    <option *ngFor="let jogador of jogadores" [value]="jogador.id">{{ jogador.nome }}</option>
                  </select>
                </div>
                <div class="mb-3">
                  <label class="form-label">Data</label>
                  <input type="date" class="form-control" [(ngModel)]="desculpaEmEdicao.data">
                </div>
                <div class="mb-3">
                  <label class="form-label">Descrição</label>
                  <textarea class="form-control" rows="3" [(ngModel)]="desculpaEmEdicao.descricao"></textarea>
                </div>
                <div class="d-flex gap-2">
                  <button class="btn btn-success" (click)="salvarEdicao()">
                    <i class="bi bi-check-lg"></i> Salvar
                  </button>
                  <button class="btn btn-secondary" (click)="cancelarEdicao()">
                    <i class="bi bi-x-lg"></i> Cancelar
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Aba de Cadastro -->
    <div class="tab-pane fade" id="cadastrar" role="tabpanel" aria-labelledby="cadastrar-tab">
      <div class="card mt-3">
        <div class="card-header">
          <h5>Registrar Nova Desculpa</h5>
        </div>
        <div class="card-body">
          <form (ngSubmit)="salvarDesculpa()">
            <div class="mb-3">
              <label for="jogador" class="form-label">Jogador *</label>
              <select 
                id="jogador" 
                class="form-select" 
                [(ngModel)]="novaDesculpa.jogadorId"
                (change)="onJogadorSelecionado()"
                name="jogador"
                required>
                <option value="">Selecione um jogador</option>
                <option *ngFor="let jogador of jogadores" [value]="jogador.id">{{ jogador.nome }}</option>
              </select>
            </div>

            <div class="mb-3">
              <label for="data" class="form-label">Data *</label>
              <input 
                type="date" 
                id="data" 
                class="form-control" 
                [(ngModel)]="novaDesculpa.data"
                name="data"
                required>
            </div>

            <div class="mb-3">
              <label for="descricao" class="form-label">Descrição da Desculpa *</label>
              <textarea 
                id="descricao" 
                class="form-control" 
                rows="4" 
                [(ngModel)]="novaDesculpa.descricao"
                name="descricao"
                placeholder="Descreva o motivo da ausência..."
                required></textarea>
            </div>

            <div class="d-flex justify-content-end gap-2">
              <button type="button" class="btn btn-secondary" (click)="resetarFormulario()">
                <i class="bi bi-arrow-counterclockwise"></i> Limpar
              </button>
              <button type="submit" class="btn btn-primary">
                <i class="bi bi-save"></i> Salvar Desculpa
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
